# Generated by Django 3.0.3 on 2020-03-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_accesstoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesstoken',
            old_name='user_id',
            new_name='user',
        ),
    ]
