# Generated by Django 3.0.3 on 2020-03-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sessions_stored_replay'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stored_replay',
            new_name='StoredReplay',
        ),
        migrations.AlterModelOptions(
            name='sessions',
            options={},
        ),
    ]
