# Generated by Django 3.0.3 on 2020-03-22 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200322_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessions',
            options={'managed': False},
        ),
    ]
