# Generated by Django 3.0.3 on 2020-03-22 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200322_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedreplay',
            name='session_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Sessions'),
        ),
    ]
