# Generated by Django 3.0.3 on 2020-03-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200322_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storedreplay',
            old_name='session_id',
            new_name='session',
        ),
    ]
