# Generated by Django 3.0.4 on 2020-03-31 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_appsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedreplay',
            name='sequence',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('operator', 'Operator')], max_length=20),
        ),
    ]
